examples.http, input/ch.fhir.ig.ch-epr-mhealth.xml, input/examples/bundle/PDQm-Response.json, input/examples/patient/FranzMusterNeedsAbsoluteUrl.xml, input/examples/patient/PatientPIXmFeed.xml, input/fsh/instances.fsh, input/images-source/PDQm_ActorDiagram_ITI-78.plantuml, input/images-source/overview.plantuml, input/includes/menu.xml, input/pagecontent/capstatements.xml, input/pagecontent/index.md, input/pagecontent/iti-78.md, input/pagecontent/iti-pdqm.md, input/pagecontent/openissues.md, input/pagecontent/profiles.md, input/pagecontent/transactions.md, input/resources/capabilitystatement/CH.mHealth.API.xml, input/resources/capabilitystatement/CH.mHealth.App.xml
Add PDQm profile with actors / transaction / example and capability statement
=> PDQm profile

input/fsh/ex-audit-65.fsh, input/pagecontent/openissues.md
=> Remove URN-prefix in AuditEvent.source.site

input/examples/parameters/ParametersPIXmInput.json, input/pagecontent/iti-83.md, input/pagecontent/openissues.md, input/resources/operationdefinition/CH.PIXm.xml, input/resources/structuredefinition/ch-pixm-in-parameters.xml
=> The targetSystem in PIXm queries shall be the MPI-PID and the EPR-SPID

input/fsh/atna_capabilitystatements.fsh, input/pagecontent/openissues.md
Fixes #107
Actor names (_Audit Record Repository_ and _Audit Creator_) are from the [BALP](https://profiles.ihe.net/ITI/BALP/index.html) profile.
=> Add missing CapabilityStatements for the RESTful ATNA profile

input/examples/patient/PatientPIXmFeed.xml, input/pagecontent/iti-104.md, input/pagecontent/openissues.md, input/resources/structuredefinition/ch-pixm-patient.xml
=> PIXm Feed: update requirements to the new Amendment 1 of Annex 5 EPRO-FDHA

input/pagecontent/iti-90.md
Does this need an entry in the changelog?
=> Fix broken link to eHealthSuisse specifications in ITI-90

input/ch.fhir.ig.ch-epr-mhealth.xml, input/examples/organization/GruppenpraxisCH.xml, input/images-source/3_02_mhealthread_smartonfhir_hp_option.plantuml, input/images-source/step_mh_pixm.plantuml.txt, input/pagecontent/iti-83.md, input/pagecontent/operations.xml, input/resources/operationdefinition/CH.PIXm.xml, input/resources/structuredefinition/ch-pdqm-provider-organization.xml
=> Fix diagrams and uniformize artifact names

input/pagecontent/index.md
Fixes #140
Preview: https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/branches/ql_issue_140/index.html
=> Add a note about CH:ATC in the index

input/pagecontent/iti-78.md, input/pagecontent/openissues.md
Fixes #149 and add missing changelog entry for https://github.com/ehealthsuisse/ch-epr-mhealth/pull/145
=> Update changelog and remove fhirVersion from Accept header examples

input/ch.fhir.ig.ch-epr-mhealth.xml, input/pagecontent/iti-103.md, input/pagecontent/iti-104.md, input/pagecontent/iti-65.md, input/pagecontent/iti-66.md, input/pagecontent/iti-67.md, input/pagecontent/iti-68.md, input/pagecontent/iti-71.md, input/pagecontent/iti-78.md, input/pagecontent/iti-83.md, input/pagecontent/iti-90.md, input/pagecontent/openissues.md
Incorporate the changes to be published in IUA Trial Implementation in 2024 and fix broken links
=> Incorporate iua cp 1288

input/examples/bundle/Bundle-FindDocumentReferences.json, input/examples/bundle/Bundle-FindSubmissionSets.json, input/fsh/ppqm_consent.fsh, input/fsh/ppqm_retrieve_response_bundle.fsh, input/pagecontent/iti-65.md, input/pagecontent/iti-66.md, input/pagecontent/iti-67.md, input/pagecontent/iti-68.md, input/pagecontent/openissues.md, input/resources/capabilitystatement/CH.MHD.DocumentConsumer.xml, input/resources/capabilitystatement/CH.MHD.DocumentResponder.xml
https://github.com/ehealthsuisse/ch-epr-fhir/issues/165 [require patient.identifier](https://github.com/ehealthsuisse/ch-epr-fhir/commit/e02d2bc94cf34eb8dd595349fe302307433927c8)
https://github.com/ehealthsuisse/ch-epr-fhir/issues/170 [mhd: add creation search parameter](https://github.com/ehealthsuisse/ch-epr-fhir/commit/3389a84b90a0b124f389be2ec512828afdede6cc)
additionaly this PR fixes the pqqm errors in the ig publsiher
=> MHD: EPR-SPID for query and additional search parameter

input/pagecontent/iti-71.md
fix encoding accoding to discussion
non urlencoded / not escaped in json
url encoded in http request
=> epr-spid encoding #174

input/ch.fhir.ig.ch-epr-fhir.xml, input/examples/auditevent/ex-auditProvideBundle-source.json, input/pagecontent/changelog.md, input/pagecontent/tracecontext.md, input/resources/structuredefinition/ch-epr-fhir-auditevent.xml
@oliveregger could you please review the changes:
- Profile: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/tracecontext_mz/StructureDefinition-ch-epr-fhir-auditevent.html
- Example: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/tracecontext_mz/AuditEvent-ex-auditProvideBundle-source.json.html
- I had to adapt the patient slice in the example
- Trace context page: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/tracecontext_mz/tracecontext.html
- Changelog: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/tracecontext_mz/changelog.html
=> add AuditTrail profile #185

input/images-source/3_02_write_hcp.plantuml, input/images-source/3_02_write_tcu.plantuml, input/images-source/step_mh_mhd_pub.plantuml.txt, input/pagecontent/sequencediagrams.md
the PR adds two sequence diagrams
- User Access from an integrated Primary System to publish documents
- Writing documents from clinical archives
see https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/oe_seqdiag/sequencediagrams.html
=> update publication seq diagrams #192

input/fsh/ppqm_consent.fsh
=> Fix allowed policy references

input/fsh/ppqm_consent.fsh, input/pagecontent/ppqm.md
=> close #217

input/fsh/mhd.fsh, input/pagecontent/changelog.md
=> MHD: make the DocumentReference title mandatory (#219)

input/fsh/pdqm.fsh, input/pagecontent/changelog.md, input/pagecontent/iti-78.md
=> PDQm: fix the name search parameter (#212)

input/fsh/mhd.fsh, input/pagecontent/changelog.md
=> MHD: fix minimal cardinality of extension slice in the SubmissionSet (#211)

input/pagecontent/changelog.md, input/pagecontent/iti-67.md
=> MHD: specify usage of token search parameters in ITI-67

input/examples/bundle/2-7-BundleProvideDocument.json, input/pagecontent/ch-mhd-1.md, input/pagecontent/changelog.md, input/pagecontent/index.md, input/pagecontent/iti-104.md, input/pagecontent/iti-20.md, input/pagecontent/iti-65.md, input/pagecontent/iti-67.md, input/pagecontent/iti-68.md, input/pagecontent/iti-78.md, input/pagecontent/iti-83.md, input/pagecontent/iti-90.md
=> MHD: update the IG version in references (#213)

input/pagecontent/ch-mcsd-1.md, input/pagecontent/ch-mhd-1.md, input/pagecontent/changelog.md, input/pagecontent/iti-103.md, input/pagecontent/iti-104.md, input/pagecontent/iti-119.md, input/pagecontent/iti-20.md, input/pagecontent/iti-65.md, input/pagecontent/iti-67.md, input/pagecontent/iti-68.md, input/pagecontent/iti-71.md, input/pagecontent/iti-83.md, input/pagecontent/iti-90.md, input/pagecontent/ppq-3.md, input/pagecontent/ppq-4.md, input/pagecontent/ppq-5.md
=> Uniformize the traceparent requirement wording on transaction pages

input/ch.fhir.ig.ch-epr-fhir.xml, input/fsh/auditevents.fsh, input/fsh/mcsd_practitionerrole.fsh, input/fsh/mhd_auditevent.fsh, input/fsh/mhd_capabilitystatements.fsh, input/fsh/pdqm.fsh, input/fsh/ppqm_consent.fsh, input/ignoreWarnings.txt, input/pagecontent/changelog.md, input/resources/capabilitystatement/CH.EPR.API.xml, input/resources/capabilitystatement/CH.EPR.App.xml, input/resources/capabilitystatement/CH.PIXm.Consumer.xml, input/resources/capabilitystatement/CH.PIXm.Manager.xml, input/resources/capabilitystatement/CH.PIXm.Source.xml, input/resources/operationdefinition/CH.PIXm.xml, input/resources/structuredefinition/ch-epr-fhir-birthname.xml, input/resources/structuredefinition/ch-epr-fhir-humanname.xml, publication-request.json
- added open issues
- switch deprecated discriminator type 'pattern' to 'value' [#239](https://github.com/ehealthsuisse/ch-epr-fhir/issues/239)
- set status for extensions, profiles and datatypes to active [#244](https://github.com/ehealthsuisse/ch-epr-fhir/issues/244)
=> prepare for release 4.0.1

input/pagecontent/changelog.md, input/pagecontent/iti-71.md
Shall be reviewed in the upcoming meeting on February 13, 2025.
=> #245 conflict between auth2 scope and iti 71 scope

input/fsh/pdqm.fsh, input/pagecontent/changelog.md, sushi-config.yaml
Fixes #281 
Preview: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/281-upgrade-to-pdqm-310/
=> Upgrade PDQm to v3.1.0 #281

input/fsh/ppqm_auditevent.fsh, input/pagecontent/changelog.md, sushi-config.yaml
(Partially) fixes #278
Preview: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/278-upgrade-to-mcsd-390/qa.html
=> Upgrade mCSD to v3.9.0 #278

input/fsh/identifier.fsh, input/fsh/mhd.fsh, input/fsh/mhd_capabilitystatements.fsh, input/fsh/pdqm.fsh, input/fsh/pixm.fsh, input/fsh/ppqm_consent.fsh, input/pagecontent/StructureDefinition-PpqmConsent-mappings-intro.md, input/pagecontent/ch-mhd-1.md, input/pagecontent/index.md, input/pagecontent/iti-71.md, input/pagecontent/iti-iua.md, input/pagecontent/ppqm.md, input/resources/capabilitystatement/CH.PIXm.Source.xml, sushi-config.yaml
Preview: https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/ql_typos/
=> Fix some typos

input/examples/bundle/Bundle-FindDocumentReferences.json, input/fsh/mhd.fsh, input/pagecontent/ch-mhd-1.md, input/pagecontent/changelog.md
see https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/oe_mhd_removedate/qa.html
=> MHD: invalid mapping of the creation time, remove date #299

input/pagecontent/changelog.md, input/pagecontent/iti-130.md
=> adapt wording #310

input/fsh/identifier.fsh, input/fsh/mhd.fsh, input/pagecontent/changelog.md
see https://build.fhir.org/ig/ehealthsuisse/ch-epr-fhir/branches/oe_dicom_studyinstance/StructureDefinition-ch-mhd-documentreference-comprehensive.html
=> #294 mapping DICOM Studyinstance UID

input/fsh/Aliases.fsh, input/fsh/pdqm.fsh, input/pagecontent/ch-atc.md, input/pagecontent/ch-mhd-1.md, input/pagecontent/changelog.md, input/pagecontent/index.md, input/pagecontent/iti-65.md, input/pagecontent/iti-67.md, input/pagecontent/iti-68.md, input/pagecontent/iti-81.md, input/pagecontent/iti-iua.md, input/pagecontent/iti-mcsd.md, input/pagecontent/iti-mhd.md, input/pagecontent/iti-pdqm.md, input/pagecontent/iti-pixm.md, input/pagecontent/iti-restful-atna.md, input/pagecontent/ppq-3.md, input/pagecontent/ppq-4.md, input/pagecontent/ppq-5.md, input/pagecontent/ppqm.md
1. adding the same option to IUA as for XUA (Workflow Initiator Option, Technical User Option, Proxy Option) with required grouping
2. add grouping to the profiles with IUA 
3. minor adjustments to CH ATC tbd
4. minor adjustment to wording in transactions for mTLS with XUA
=> #307, #267, #265 : atna grouping

input/fsh/ppqm_consent.fsh
This is a proposal to address the issue described in #251.
=> allow literal references in CH:PPQm

input/includes/menu.xml, input/pagecontent/ch-atc.md, input/pagecontent/changelog.md, input/pagecontent/iti-81.md, sushi-config.yaml
CH:ATC: Updated references and minor textual corrections in CH:ATC, ITI-81 and Volume 3
Resolves: https://github.com/ehealthsuisse/ch-epr-fhir/issues/323, https://github.com/ehealthsuisse/ch-epr-fhir/issues/324, https://github.com/ehealthsuisse/ch-epr-fhir/issues/326, https://github.com/ehealthsuisse/ch-epr-fhir/issues/327
=> CH:ATC: Updated references and minor textual corrections in CH:ATC, ITI-81 and Volume 3

input/pagecontent/changelog.md, input/pagecontent/ppqm.md
=> CH:PPQm: Minor textual corrections and update of links

input/fsh/Aliases.fsh, input/fsh/mhd.fsh, input/pagecontent/changelog.md
…ntReference Comprehensive [#318]
=> DocumentReference.context.event ValueSet

input/images-source/3_02_read_hcp.plantuml, input/images-source/3_02_read_pat.plantuml, input/images-source/3_02_write_hcp.plantuml, input/images-source/3_02_write_tcu.plantuml, input/pagecontent/changelog.md
=> #357 add mTLS to seq diagrams
